version: "2.14.0"

services:
  jaeger:
    image: 'jaegertracing/opentelemetry-all-in-one'
    ports:
      - '13133:13133'
      - '16686:16686'
      - '55680:55680'
    network_mode: "host"

  prometheus:
    image: prom/prometheus
    container_name: prometheus-service
    ports:
      - 19090:9090
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: "host"
  
  grafana:
    image: grafana/grafana
    container_name: grafana-service
    ports:
      - 3000:3000
    network_mode: "host"
    depends_on:
      - prometheus
    # volumes: 
    #   - ./grafana/provisioning/:/etc/grafana/provisioning/